### ISSUE TITLE
schedule page returns 404

### ISSUE THREAD

**Issue by ridhof** [grikomsn/improved-happiness#1]
**Describe the bug**
Clicking a `schedule` menu from the navigation bar in the footer will redirect user into `https://nibras.co/schedule`. It should render a schedule page to schedule an appointment. But currently it returns 404 - this page could not be found.

**To Reproduce**
1. Go to 'https://nibras.co'
2. Click on 'schedule
3. See error

**Expected behavior**
A schedule page to choose a date for an appointment.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 119

**Comment by grikomsn** [comment]
fixed https://github.com/grikomsn/improved-happiness/commit/af2d459271af38d4ba362452fd3bbd731e4a9231
